dist: xenial
language: python
python: 3.7
before_install:
  - python --version
install:
  - pip install -r requirements.txt
  - travis_retry pip install --upgrade pylint>=2.1.1
script:
  - |
      pylint --version
      pylint bug;